apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Wordpress
spec:
  destination:
    name: ""
    namespace: wordpress
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "HEAD"
    chart: wordpress
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
